### ISSUE TITLE
Crash if client connection receives data after timeout

### ISSUE THREAD

**Issue by johngiffin** [tpitale/coap_ex#12]
When the client times out waiting for a response and then receives a response from the server, the following error happens:

```[debug]  CoAP socket received raw data 64 45 00 01 F9 B0 94 0D from {{10, 115, 214, 230}, 5683}
[error]  GenServer #PID<0.532.0> terminating
** (ArgumentError) argument error
    :erlang.cancel_timer(nil)
    (coap_ex) lib/coap/connection.ex:460: CoAP.Connection.cancel_timer/1
    (coap_ex) lib/coap/connection.ex:298: CoAP.Connection.receive_message/2
    (coap_ex) lib/coap/connection.ex:147: CoAP.Connection.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:receive, %CoAP.Message{code_class: 2, code_detail: 5, message_id: 1, method: nil, multipart: %CoAP.Multipart{control: nil, description: nil, more: false, multipart: false, number: 0, requested_number: 0, requested_size: 0, size: 0}, options: %{}, payload: "", request: false, status: {:ok, :content}, token: <<249, 176, 148, 13>>, type: :ack, version: 1}}
State: %CoAP.Connection.State{handler: #PID<0.534.0>, in_payload: %CoAP.Payload{data: "", multipart: false, segments: [], size: nil}, ip: "10.115.214.230", message: %CoAP.Message{code_class: 0, code_detail: 1, message_id: 1, method: :get, multipart: nil, options: %{uri_path: ["", ""]}, payload: <<34, 14, 8, 1, 16, 165, 217, 214, 230, 5, 24, 165, 194, 230, 230, 5>>, request: true, status: nil, token: <<249, 176, 148, 13>>, type: :con, version: 1}, next_message_id: 41386, out_payload: %CoAP.Payload{data: <<34, 14, 8, 1, 16, 165, 217, 214, 230, 5, 24, 165, 194, 230, 230, 5>>, multipart: false, segments: [], size: 512}, phase: :awaiting_peer_ack, port: 5683, retries: 0, retry_timeout: 1840, server: #PID<0.533.0>, timer: nil, token: <<249, 176, 148, 13>>}
[error]  GenServer #PID<0.533.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:badarg, [{:erlang, :cancel_timer, [nil], []}, {CoAP.Connection, :cancel_timer, 1, [file: 'lib/coap/connection.ex', line: 460]}, {CoAP.Connection, :receive_message, 2, [file: 'lib/coap/connection.ex', line: 298]}, {CoAP.Connection, :handle_info, 2, [file: 'lib/coap/connection.ex', line: 147]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.INET, Postgrex.MACADDR, Postgrex.Query, Time, URI, Version, Version.Requirement
    (elixir) /private/tmp/elixir-20180825-41637-j0b7x7/elixir-1.7.3/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) /private/tmp/elixir-20180825-41637-j0b7x7/elixir-1.7.3/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
    (coap_ex) lib/coap/socket_server.ex:115: CoAP.SocketServer.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.1866616307.2279866370.163823>, :process, #PID<0.532.0>, {:badarg, [{:erlang, :cancel_timer, [nil], []}, {CoAP.Connection, :cancel_timer, 1, [file: 'lib/coap/connection.ex', line: 460]}, {CoAP.Connection, :receive_message, 2, [file: 'lib/coap/connection.ex', line: 298]}, {CoAP.Connection, :handle_info, 2, [file: 'lib/coap/connection.ex', line: 147]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
State: %{connections: %{{{10, 115, 214, 230}, 5683, <<249, 176, 148, 13>>} => #PID<0.532.0>}, endpoint: {CoAP.Adapters.Client, #PID<0.531.0>}, monitors: %{#Reference<0.1866616307.2279866370.163823> => {{10, 115, 214, 230}, 5683, <<249, 176, 148, 13>>}}, port: 0, socket: #Port<0.27>}
[debug]  CoAP socket received DOWN:noproc in CoAP.SocketServer from:{{10, 115, 214, 230}, 5683, <<249, 176, 148, 13>>}```

**Comment by tpitale** [comment]
Okay, so the connection should be exiting … or perhaps set to a different phase (like `app_ack_sent`) at the point of the timeout.

I'll see if I can determine what it _should_ do based on the spec.

**Comment by tpitale** [comment]
There appears to be no details on this handling in the spec. Nor does it appear to say what to do if a message is received after the end of the communication exchange except this:

> In case a message carrying a response is unexpected (the client is
> not waiting for a response from the identified endpoint, at the
> endpoint addressed, and/or with the given token), the response is
> rejected (Sections 4.2 and 4.3).

**Comment by tpitale** [comment]
As per https://tools.ietf.org/html/rfc7252#section-4.2 it may be the correct answer is that the connection is in a phase which rejects new messages with RST responses. I'm thinking that `app_ack_sent` is correct.
